version: 2.1

orbs: 
    python: circleci/python@2.0.3
    aws-cli: circleci/aws-cli@3.1.1

jobs:
  lint-code:
    executor: python/default
    steps:
      - checkout
      - run: pip install autopep8 && autopep8 --in-place --aggressive --aggressive *.py

  run-test:
    executor: python/default
    steps:
      - checkout
      - run: pip install flake8 && flake8

  create-infrastructure:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run:
          name: Create Cloudformation Stack
          command: |
            cd infrastructure
            chmod u+x ./create.sh ./update_inventory.sh
            mkdir -m 777 -p /temp
            echo "[web]" > /temp/inventroy.txt
      
      - persisit_to_workspace:
          root: temp
          paths:
            - inventory.txt
        



  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["48:64:38:1c:02:ab:7d:c6:91:75:b9:f9:12:b1:26:e0"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run: 
          name: copy application files
          command: |
            cp -r requirements.txt templates/ app.py infrastructure/roles/deploy/files
      
      - attach_workspace:
          at: /temp

      - run: 
          name: Configure Server
          command: |
            cd infrastructure/
            cp -r /temp/inventory.txt .
            cat inventory.txt
            ansible-playbook -i inventory.txt main.yaml 

workflows:
  main:
    jobs:
      - lint-code
      - run-test:
          requires:
            - lint-code
      - create-infrastructure:
          requires:
            - run-test
      - configure-infrastructure:
          requires:
            - create-infrastructure
