version: 2.1

orbs: 
    python: circleci/python@2.0.3

jobs:
  lint-code:
    executor: python/default
    steps:
      - checkout
      - run: pip install autopep8 && autopep8 --in-place --aggressive --aggressive *.py

  run-test:
    executor: python/default
    steps:
      - checkout
      - run: pip install flake8 && flake8

workflows:
  main:
    jobs:
      - lint-code
      - run-test
