version: 2.1

orbs: 
    python: circleci/python@2.0.3

jobs:
  lint-code:
    executor: python/default
    steps:
      - checkout
      - python/dist
      - run: pip install autopep8 && autopep8 --in-place --aggressive --aggressive *.py

workflows:
  main:
    jobs:
      - lint-code
      - python/test:
          test-tool: flake8
