Parameters:
  EnvironmentName:
    Description: Name to Recognize this specific Project
    Type: String
    Default: Refidas

  DefaultZone:
    Description: Default Zone for the machine
    Type: String

Resources:
  RefidasGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows Http and ssh
      GroupName: Refidas Group
      SecurityGroupIngress:
        - ToPort: 22
          FromPort: 22
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp

        - ToPort: 80
          FromPort: 80
          CidrIp: 0.0.0.0/0
          IpProtocol: tcp
  
  TestMachine:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref DefaultZone
      ImageId: ami-052efd3df9dad4825
      InstanceType: t2.micro
      KeyName: refidas
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
      SecurityGroups: 
        - Ref: RefidasGroup 
Outputs:
  MachinePublicAddress:
    Value: !GetAtt TestMachine.PublicIp
    Description: Public Address of TestMachine
